const actionTypes = Object.freeze({
    //app
    APP_START_UP_COMPLETE: 'APP_START_UP_COMPLETE',
    SET_CONTENT_OF_CONFIRM_MODAL: 'SET_CONTENT_OF_CONFIRM_MODAL',
    CHANGE_LANGUAGE: 'CHANGE_LANGUAGE',

    //user
    ADD_USER_SUCCESS: 'ADD_USER_SUCCESS',
    USER_LOGIN_SUCCESS: 'USER_LOGIN_SUCCESS',
    USER_LOGIN_FAIL: 'USER_LOGIN_FAIL',
    PROCESS_LOGOUT: 'PROCESS_LOGOUT',

    ///admin
    FETCH_GENDER_USER: 'FETCH_GENDER_USER',
    FETCH_GENDER_SUCCESS: 'FETCH_GENDER_SUCCESS',
    FETCH_GENDER_FAILED: 'FETCH_GENDER_USER',

    FETCH_POSITION_USER: 'FETCH_POSITION_USER',
    FETCH_POSITION_SUCCESS: 'FETCH_POSITION_SUCCESS',
    FETCH_POSITION_FAILED: 'FETCH_POSITION_USER',

    FETCH_ROLE_USER: 'FETCH_ROLE_USER',
    FETCH_ROLE_SUCCESS: 'FETCH_ROLE_SUCCESS',
    FETCH_ROLE_FAILED: 'FETCH_ROLE_FAILED',

    CREATE_USER_SUCCESS: 'CREATE_USER_SUCCESS',
    CREATE_USER_FAILED: 'CREATE_USER_FAILED',


    FETCH_GET_ALL_SUCCESS: 'FETCH_GET_ALL_SUCCESS',
    FETCH_GET_ALL_FAILED: 'FETCH_GET_ALL_FAILED',

    DELETE_USER_SUCCESS: 'DELETE_USER_SUCCESS',
    DELETE_USER_FAILED: 'DELETE_USER_FAILED',

    EDIT_USER_SUCCESS: 'EDIT_USER_SUCCESS',
    EDIT_USER_FAILED: 'EDIT_USER_FAILED',

    FETCH_TOP_DOCTOR_SUCCESS: 'FETCH_TOP_DOCTOR_SUCCESS',
    FETCH_TOP_DOCTOR_FAILED: 'FETCH_TOP_DOCTOR_FAILED',

    FETCH_ALL_DOCTOR_SUCCESS: 'FETCH_ALL_DOCTOR_SUCCESS',
    FETCH_ALL_DOCTOR_FAILED: 'FETCH_ALL_DOCTOR_FAILED',

    SAVE_DETAILS_DOCTOR_SUCCESS: 'SAVE_DETAILS_DOCTOR_SUCCESS',
    SAVE_DETAILS_DOCTOR_FAILED: 'SAVE_DETAILS_DOCTOR_FAILED',

    GET_DETAILS_DOCTOR_SUCCESS: 'GET_DETAILS_DOCTOR_SUCCESS',
    GET_DETAILS_DOCTOR_FAILED: 'GET_DETAILS_DOCTOR_FAILED',

    GET_ALL_CODE_TIME_SUCCESS: 'GET_ALL_CODE_TIME_SUCCESS',
    GET_ALL_CODE_TIME_FAILED: 'GET_ALL_CODE_TIME_FAILED',

    FETCH_ALL_REQUIRED_DOCTOR_INFOR_SUCCESS: 'FETCH_ALL_REQUIRED_DOCTOR_INFOR_SUCCESS',
    FETCH_ALL_REQUIRED_DOCTOR_INFOR_FAILED: 'FETCH_ALL_REQUIRED_DOCTOR_INFOR_FAILED',

    GET_ALL_CLINIC_SUCCESS : 'GET_ALL_CLINIC_SUCCESS',
    GET_ALL_CLINIC_FAILED : 'GET_ALL_CLINIC_FAILED',
    GET_ALL_SPECIALTY_SUCCESS : 'GET_ALL_SPECIALTY_SUCCESS',
    GET_ALL_SPECIALTY_FAILED : 'GET_ALL_SPECIALTY_FAILED',

    GET_ALL_HANDBOOK_SUCCESS : 'GET_ALL_HANDBOOK_SUCCESS',
    GET_ALL_HANDBOOK_FAILED : 'GET_ALL_HANDBOOK_FAILED',

    GET_SCHEDULE_BY_DATE_SUCCESS : 'GET_SCHEDULE_BY_DATE_SUCCESS',
    GET_SCHEDULE_BY_DATE_FAILED : 'GET_SCHEDULE_BY_DATE_FAILED',

    GET_PATIENT_INFOR_SUCCESS : 'GET_PATIENT_INFOR_SUCCESS',
    GET_PATIENT_INFOR_FAILED : 'GET_PATIENT_INFOR_FAILED',

    GET_PATIENT_NO_COMFIRM_SUCCESS : 'GET_PATIENT_NO_COMFIRM_SUCCESS',
    GET_PATIENT_NO_COMFIRM_FAILED : 'GET_PATIENT_NO_COMFIRM_FAILED',

    GET_PATIENT_FINISHED_SUCCESS : 'GET_PATIENT_FINISHED_SUCCESS',
    GET_PATIENT_FINISHED_FAILED : 'GET_PATIENT_FINISHED_FAILED',

    GET_ALL_PATIENTS_BY_DOCTOR_SUCCESS : 'GET_ALL_PATIENTS_BY_DOCTOR_SUCCESS',
    GET_ALL_PATIENTS_BY_DOCTOR_FAILED : 'GET_ALL_PATIENTS_BY_DOCTOR_FAILED'

})

export default actionTypes;